name: vertexai_walkthrough
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  file_picker: ^8.0.3
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.5
  firebase_vertexai: ^0.1.0
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.20
  image_picker: ^1.1.1
  path: ^1.9.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
